In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
order_items = pd.read_csv("/content/drive/MyDrive/Sales/order_items.csv")
orders = pd.read_csv("/content/drive/MyDrive/Sales/orders.csv")
customers = pd.read_csv("/content/drive/MyDrive/Sales/customers.csv")
products = pd.read_csv("/content/drive/MyDrive/Sales/products.csv")

In [ ]:
sales_master = orders.merge(order_items,how = 'outer')

In [ ]:
sales_master = sales_master.merge(customers,how='outer')

In [ ]:
sales_master = sales_master.merge(products,how='outer')

In [ ]:
sales_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  object
 4   order_approved_at              113264 non-null  object
 5   order_delivered_carrier_date   111457 non-null  object
 6   order_delivered_customer_date  110196 non-null  object
 7   order_estimated_delivery_date  113425 non-null  object
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  object
 10  seller_id                      112650 non-null  object
 11  shipping_limit_date            112650 non-null  object
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  customer_unique_id             113425 non-null  object
 15  customer_zip_code_prefix       113425 non-null  int64
 16  customer_city                  113425 non-null  object
 17  customer_state                 113425 non-null  object
 18  product_category_name          111047 non-null  object
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
dtypes: float64(10), int64(1), object(15)
memory usage: 22.5+ MB

In [ ]:
sales_master.dtypes

order_id                          object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
order_item_id                    float64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
customer_unique_id                object
customer_zip_code_prefix           int64
customer_city                     object
customer_state                    object
product_category_name             object
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
dtype: object

In [ ]:
sales_master.shape

(113425, 26)

In [ ]:
date_col = ['order_approved_at','order_purchase_timestamp','order_delivered_carrier_date','order_delivered_customer_date',
            'order_estimated_delivery_date', 'shipping_limit_date']
sales_master[date_col] = sales_master[date_col].apply(
    pd.to_datetime,
    errors = 'coerce'
)

In [ ]:
sales_master['revenue'] = sales_master['price'] + sales_master['freight_value']

In [ ]:
print(sales_master)

                                order_id                       customer_id  \
0       f30149f4a8882a08895b6a242aa0d612  86c180c33f454b35e1596a99da3dddc4
1       f5eda0ded77c1293b04c953138c8331d  68f2b37558e27791155db34bcded5ac0
2       0bf736fd0fd5169d60de3699fcbcf986  6cd217b674e22cf568f6a2cf6060fd07
3       3aba44d8e554ab4bb8c09f6f78032ca8  82b838f513e00463174cc7cae7e76c1f
4       6f0dfb5b5398b271cc6bbd9ee263530e  8517e7c86998bf39a540087da6f115d9
...                                  ...                               ...
113420  87ae60ef8b08ae0e5f903cacb53a6904  fea4d57ed3a45455f89c25ef3dae8ee8
113421  d69fcef5a5fe3a3db60ea65c6ee499cc  ff0340330283c0d05ea7281e67fa2e76
113422  f86d7bc39aab05299691322044b63bb2  ff31bee1ba4bba00cc14b1b91c8d28f3
113423  74f833bf7c70ce8c3f820f725c213e1c  fffc22669ca576ae3f654ea64c8f36be
113424  2e935fa1d39497aa0ec3f1107fbfb5b8  ffffe8b65bbe3087b653a978c870db99

       order_status order_purchase_timestamp   order_approved_at  \
0         delivered      2018-05-20 18:45:21 2018-05-20 18:58:59
1         delivered      2017-12-12 19:20:28 2017-12-12 19:32:19
2         delivered      2017-12-21 16:21:47 2017-12-22 17:31:27
3         delivered      2018-08-10 13:24:35 2018-08-10 13:35:21
4         delivered      2018-08-01 22:00:33 2018-08-01 22:15:19
...             ...                      ...                 ...
113420     canceled      2018-09-11 16:45:54                 NaT
113421  unavailable      2017-12-02 10:11:44 2017-12-02 10:30:31
113422     canceled      2018-08-13 18:43:06                 NaT
113423  unavailable      2017-06-30 11:21:11 2017-06-30 11:30:20
113424  unavailable      2017-09-29 14:07:03 2017-10-03 06:34:13

       order_delivered_carrier_date order_delivered_customer_date  \
0               2018-05-21 16:09:00           2018-06-06 22:11:56
1               2017-12-20 20:12:42           2017-12-23 17:11:51
2               2018-01-02 22:27:47           2018-01-06 15:03:41
3               2018-08-13 14:43:00           2018-08-17 21:33:40
4               2018-08-02 14:20:00           2018-08-07 17:38:52
...                             ...                           ...
113420                          NaT                           NaT
113421                          NaT                           NaT
113422                          NaT                           NaT
113423                          NaT                           NaT
113424                          NaT                           NaT

       order_estimated_delivery_date  order_item_id  \
0                         2018-06-20            1.0
1                         2018-01-05            1.0
2                         2018-01-16            1.0
3                         2018-08-27            1.0
4                         2018-08-24            1.0
...                              ...            ...
113420                    2018-09-26            NaN
113421                    2018-01-08            NaN
113422                    2018-09-25            NaN
113423                    2017-08-01            NaN
113424                    2017-10-24            NaN

                              product_id  ... customer_state  \
0       00066f42aeeb9f3007548bb9d3f33c38  ...             RS
1       00088930e925c41fd95ebfe695fd2655  ...             SP
2       0009406fd7479715e4bef61dd91f2462  ...             SP
3       000b8f95fcb9e0096488278317764d19  ...             RS
4       000b8f95fcb9e0096488278317764d19  ...             RS
...                                  ...  ...            ...
113420                               NaN  ...             SP
113421                               NaN  ...             AL
113422                               NaN  ...             RO
113423                               NaN  ...             BA
113424                               NaN  ...             SP

        product_category_name  product_name_lenght  \
0                  perfumaria                 53.0
1                  automotivo                 56.0
2             cama_mesa_banho                 50.0
3       utilidades_domesticas                 25.0
4       utilidades_domesticas                 25.0
...                       ...                  ...
113420                    NaN                  NaN
113421                    NaN                  NaN
113422                    NaN                  NaN
113423                    NaN                  NaN
113424                    NaN                  NaN

        product_description_lenght product_photos_qty  product_weight_g  \
0                            596.0                6.0             300.0
1                            752.0                4.0            1225.0
2                            266.0                2.0             300.0
3                            364.0                3.0             550.0
4                            364.0                3.0             550.0
...                            ...                ...               ...
113420                         NaN                NaN               NaN
113421                         NaN                NaN               NaN
113422                         NaN                NaN               NaN
113423                         NaN                NaN               NaN
113424                         NaN                NaN               NaN

       product_length_cm product_height_cm product_width_cm  revenue
0                   20.0              16.0             16.0   120.24
1                   55.0              10.0             26.0   143.83
2                   45.0              15.0             35.0   242.10
3                   19.0              24.0             12.0    78.50
4                   19.0              24.0             12.0    78.50
...                  ...               ...              ...      ...
113420               NaN               NaN              NaN      NaN
113421               NaN               NaN              NaN      NaN
113422               NaN               NaN              NaN      NaN
113423               NaN               NaN              NaN      NaN
113424               NaN               NaN              NaN      NaN

[113425 rows x 27 columns]

In [ ]:
sales_master['delivery_days'] = (sales_master['order_delivered_customer_date'] - sales_master['order_purchase_timestamp']).dt.days

In [ ]:
sales_master['is_late'] = np.where(sales_master['order_delivered_customer_date'] > sales_master['order_estimated_delivery_date'],1,0)

In [ ]:
sales_master[['is_late','order_delivered_customer_date','order_estimated_delivery_date']].tail(10)

        is_late order_delivered_customer_date order_estimated_delivery_date
113415        0                           NaT                    2017-03-13
113416        0                           NaT                    2017-09-01
113417        0                           NaT                    2018-03-15
113418        0                           NaT                    2018-01-22
113419        0                           NaT                    2017-11-08
113420        0                           NaT                    2018-09-26
113421        0                           NaT                    2018-01-08
113422        0                           NaT                    2018-09-25
113423        0                           NaT                    2017-08-01
113424        0                           NaT                    2017-10-24

In [ ]:
sales_master['order_month'] = sales_master['order_purchase_timestamp'].dt.month

In [ ]:
print(sales_master)

In [ ]:
sales_master['order_status'].unique()

array(['delivered', 'processing', 'shipped', 'invoiced', 'canceled',
       'unavailable', 'approved', 'created'], dtype=object)

In [ ]:
sales_master[['order_purchase_timestamp','order_month']]

       order_purchase_timestamp  order_month
0           2018-05-20 18:45:21            5
1           2017-12-12 19:20:28           12
2           2017-12-21 16:21:47           12
3           2018-08-10 13:24:35            8
4           2018-08-01 22:00:33            8
...                         ...          ...
113420      2018-09-11 16:45:54            9
113421      2017-12-02 10:11:44           12
113422      2018-08-13 18:43:06            8
113423      2017-06-30 11:21:11            6
113424      2017-09-29 14:07:03            9

[113425 rows x 2 columns]

In [ ]:
sales_master = sales_master[
    sales_master['order_status'] != 'canceled'
].reset_index(drop = True)

In [ ]:
sales_master['order_status'].unique()

array(['delivered', 'processing', 'shipped', 'invoiced', 'unavailable',
       'approved', 'created'], dtype=object)

In [ ]:
sales_master

In [ ]:
sales_master = sales_master.drop_duplicates(subset = 'order_id')

In [ ]:
print(sales_master.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  19
order_delivered_carrier_date     1233
order_delivered_customer_date    2346
order_estimated_delivery_date       0
order_item_id                     611
product_id                        611
seller_id                         611
shipping_limit_date               611
price                             611
freight_value                     611
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name            2017
product_name_lenght              2017
product_description_lenght       2017
product_photos_qty               2017
product_weight_g                  627
product_length_cm                 627
product_height_cm                 627
product_width_cm                  627
revenue                           611
delivery_days                    2346
is_late                             0
order_month                         0
dtype: int64

In [ ]:
null_index = sales_master[
sales_master['product_length_cm'].isnull()
].index
print(null_index)

Index([  4051,  42802,  42803,  42804,  42805,  42806,  42807,  42808,  42809,
        42811,
       ...
       112709, 112710, 112711, 112712, 112713, 112714, 112715, 112716, 112717,
       112718],
      dtype='int64', length=627)

In [ ]:
for i in null_index:
  print(sales_master.loc[i-5:i+5,'product_length_cm'])

Streaming output truncated to the last 5000 lines.
112297   NaN
112298   NaN
112299   NaN
112300   NaN
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
Name: product_length_cm, dtype: float64
112297   NaN
112298   NaN
112299   NaN
112300   NaN
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
Name: product_length_cm, dtype: float64
112298   NaN
112299   NaN
112300   NaN
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
Name: product_length_cm, dtype: float64
112299   NaN
112300   NaN
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
Name: product_length_cm, dtype: float64
112300   NaN
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
Name: product_length_cm, dtype: float64
112301   NaN
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
Name: product_length_cm, dtype: float64
112302   NaN
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
Name: product_length_cm, dtype: float64
112303   NaN
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
Name: product_length_cm, dtype: float64
112304   NaN
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
Name: product_length_cm, dtype: float64
112305   NaN
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
Name: product_length_cm, dtype: float64
112306   NaN
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
Name: product_length_cm, dtype: float64
112307   NaN
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
Name: product_length_cm, dtype: float64
112308   NaN
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
Name: product_length_cm, dtype: float64
112309   NaN
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
Name: product_length_cm, dtype: float64
112310   NaN
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
Name: product_length_cm, dtype: float64
112311   NaN
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
Name: product_length_cm, dtype: float64
112312   NaN
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
Name: product_length_cm, dtype: float64
112313   NaN
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
Name: product_length_cm, dtype: float64
112314   NaN
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
Name: product_length_cm, dtype: float64
112315   NaN
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
Name: product_length_cm, dtype: float64
112316   NaN
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
Name: product_length_cm, dtype: float64
112317   NaN
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
Name: product_length_cm, dtype: float64
112318   NaN
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
Name: product_length_cm, dtype: float64
112319   NaN
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
Name: product_length_cm, dtype: float64
112320   NaN
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
Name: product_length_cm, dtype: float64
112321   NaN
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
Name: product_length_cm, dtype: float64
112322   NaN
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
Name: product_length_cm, dtype: float64
112323   NaN
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
Name: product_length_cm, dtype: float64
112324   NaN
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
Name: product_length_cm, dtype: float64
112325   NaN
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
Name: product_length_cm, dtype: float64
112326   NaN
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
Name: product_length_cm, dtype: float64
112327   NaN
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
Name: product_length_cm, dtype: float64
112328   NaN
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
Name: product_length_cm, dtype: float64
112329   NaN
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
Name: product_length_cm, dtype: float64
112330   NaN
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
Name: product_length_cm, dtype: float64
112331   NaN
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
Name: product_length_cm, dtype: float64
112332   NaN
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
Name: product_length_cm, dtype: float64
112333   NaN
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
Name: product_length_cm, dtype: float64
112334   NaN
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
Name: product_length_cm, dtype: float64
112335   NaN
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
Name: product_length_cm, dtype: float64
112336   NaN
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
Name: product_length_cm, dtype: float64
112337   NaN
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
Name: product_length_cm, dtype: float64
112338   NaN
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
Name: product_length_cm, dtype: float64
112339   NaN
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
Name: product_length_cm, dtype: float64
112340   NaN
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
Name: product_length_cm, dtype: float64
112341   NaN
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
Name: product_length_cm, dtype: float64
112342   NaN
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
Name: product_length_cm, dtype: float64
112343   NaN
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
Name: product_length_cm, dtype: float64
112344   NaN
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
Name: product_length_cm, dtype: float64
112345   NaN
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
Name: product_length_cm, dtype: float64
112346   NaN
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
Name: product_length_cm, dtype: float64
112347   NaN
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
Name: product_length_cm, dtype: float64
112348   NaN
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
Name: product_length_cm, dtype: float64
112349   NaN
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
Name: product_length_cm, dtype: float64
112350   NaN
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
Name: product_length_cm, dtype: float64
112351   NaN
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
Name: product_length_cm, dtype: float64
112352   NaN
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
Name: product_length_cm, dtype: float64
112353   NaN
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
Name: product_length_cm, dtype: float64
112354   NaN
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
Name: product_length_cm, dtype: float64
112355   NaN
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
Name: product_length_cm, dtype: float64
112356   NaN
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
Name: product_length_cm, dtype: float64
112357   NaN
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
Name: product_length_cm, dtype: float64
112358   NaN
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
Name: product_length_cm, dtype: float64
112359   NaN
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
Name: product_length_cm, dtype: float64
112360   NaN
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
Name: product_length_cm, dtype: float64
112361   NaN
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
Name: product_length_cm, dtype: float64
112362   NaN
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
Name: product_length_cm, dtype: float64
112363   NaN
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
Name: product_length_cm, dtype: float64
112364   NaN
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
Name: product_length_cm, dtype: float64
112365   NaN
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
Name: product_length_cm, dtype: float64
112366   NaN
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
Name: product_length_cm, dtype: float64
112367   NaN
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
Name: product_length_cm, dtype: float64
112368   NaN
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
Name: product_length_cm, dtype: float64
112369   NaN
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
Name: product_length_cm, dtype: float64
112370   NaN
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
Name: product_length_cm, dtype: float64
112371   NaN
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
Name: product_length_cm, dtype: float64
112372   NaN
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
Name: product_length_cm, dtype: float64
112373   NaN
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
Name: product_length_cm, dtype: float64
112374   NaN
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
Name: product_length_cm, dtype: float64
112375   NaN
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
Name: product_length_cm, dtype: float64
112376   NaN
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
Name: product_length_cm, dtype: float64
112377   NaN
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
Name: product_length_cm, dtype: float64
112378   NaN
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
Name: product_length_cm, dtype: float64
112379   NaN
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
Name: product_length_cm, dtype: float64
112380   NaN
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
Name: product_length_cm, dtype: float64
112381   NaN
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
Name: product_length_cm, dtype: float64
112382   NaN
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
Name: product_length_cm, dtype: float64
112383   NaN
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
Name: product_length_cm, dtype: float64
112384   NaN
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
Name: product_length_cm, dtype: float64
112385   NaN
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
Name: product_length_cm, dtype: float64
112386   NaN
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
Name: product_length_cm, dtype: float64
112387   NaN
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
Name: product_length_cm, dtype: float64
112388   NaN
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
Name: product_length_cm, dtype: float64
112389   NaN
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
Name: product_length_cm, dtype: float64
112390   NaN
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
Name: product_length_cm, dtype: float64
112391   NaN
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
Name: product_length_cm, dtype: float64
112392   NaN
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
Name: product_length_cm, dtype: float64
112393   NaN
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
Name: product_length_cm, dtype: float64
112394   NaN
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
Name: product_length_cm, dtype: float64
112395   NaN
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
Name: product_length_cm, dtype: float64
112396   NaN
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
Name: product_length_cm, dtype: float64
112397   NaN
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
Name: product_length_cm, dtype: float64
112398   NaN
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
Name: product_length_cm, dtype: float64
112399   NaN
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
Name: product_length_cm, dtype: float64
112400   NaN
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
112410   NaN
Name: product_length_cm, dtype: float64
112401   NaN
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
112410   NaN
112411   NaN
Name: product_length_cm, dtype: float64
112402   NaN
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
112410   NaN
112411   NaN
112412   NaN
Name: product_length_cm, dtype: float64
112403   NaN
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
112410   NaN
112411   NaN
112412   NaN
112413   NaN
Name: product_length_cm, dtype: float64
112404   NaN
112405   NaN
112406   NaN
112407   NaN
112408   NaN
112409   NaN
112410   NaN
112411   NaN
112412   NaN
112413   NaN
112414   NaN
Name: product_length_cm, dtype: float64
112405   NaN

In [ ]:
sales_master.dropna(subset = ['product_length_cm'],inplace = True)

In [ ]:
sales_master['product_category_name']

In [ ]:
sales_master = sales_master[
    sales_master['order_status'] != 'unavailable'
].reset_index(drop = True)

In [ ]:
sales_master['order_approved_at'] = (sales_master['order_approved_at'].fillna(sales_master['order_purchase_timestamp']))

In [ ]:
print(sales_master)

In [ ]:
sales_master.dropna(subset= ['product_category_name'],inplace = True)

In [ ]:
sales_master.dropna(subset= ['order_delivered_customer_date'],inplace = True)

In [ ]:
sales_master.dropna(subset = ['order_delivered_carrier_date'],inplace = True)

In [ ]:
sales_master.reset_index(drop = True, inplace = True)

In [ ]:
text_cols = sales_master.select_dtypes(include = 'object').columns
sales_master[text_cols] = sales_master[text_cols].apply(lambda x : x.str.strip())

In [ ]:
print(sales_master)

In [ ]:
sales_master.to_excel(
    '/content/drive/MyDrive/sales_master.xlsx',
    index=False
)